### ISSUE TITLE
GitLab-CI Pipeline Error with PHPUnit

### ISSUE THREAD

**Issue by makakken** [aw-studio/fjord#28]
Hi,
I try to build/test/deploy a project through gitlab-ci pipeline, the following is my .gitlab-ci.yml:

stages:
  - build
  - test
  - deploy

```
image: hitalos/laravel:latest
services:
  - mysql:5

variables:
  MYSQL_DATABASE: "____"
  MYSQL_ROOT_PASSWORD: "____"

composer:
  stage: build
  # cache:
  #   key: ${CI_COMMIT_REF_SLUG}-composer
  #   paths:
  #     - vendor/
  script:
      - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - cp .env.example .env
  artifacts:
    expire_in: 30 mins
    paths:
      - vendor/
      - fjord/
      - .env

phpunit:
  stage: test
  dependencies:
    - composer
  script:
    - php artisan key:generate
    - php artisan fjord:install
    - php artisan migrate --force
    - phpunit --coverage-text --colors=never

publish:
  stage: deploy
  image: ubuntu
  only:
    - master
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
   # shortened because not relevant
```

test-case is the following:
`
public function testBasicTest()
    {
        $response = $this->get('/');
        dump($response->content());
        $response->assertStatus(200);
    }
`
(dump is only here to understand whats happening, normally test result is 200 != 500)

and routes/web.php is the following (shortened):
`
use Fjord\Support\Facades\Form;
Route::get('/', function () {
    return view('welcome')->with([
        'data' => Form::load('pages', 'home')
    ]);
});
`

So i get the following error:
`Illuminate\Contracts\Container\BindingResolutionException: Target class [fjord.form] does not exist. in file /builds/gooze/ostfjord/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 807`
